name: Build Linux Kernel

on:
  push:
    branches:
      - main

jobs:
  build_kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y curl git ftp lftp wget libarchive-tools ccache python2 python2-dev python3
        sudo apt-get install -y pngcrush schedtool dpkg-dev liblz4-tool make optipng maven device-tree-compiler 
        sudo apt-get install -y libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc
        sudo apt-get install -y libxml2-utils libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools lzop flex tree
        sudo apt-get install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev
        sudo apt-get install -y pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl 
        sudo apt-get install -y zip unzip tar gzip bzip2 rar unrar llvm g++-multilib bison gperf zlib1g-dev automake

    - name: Set up cross-compilation environment
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export LOCALVERSION=-vince
        make vince_defconfig

    - name: Build Linux Kernel
      run: make -j$(nproc)

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kernel-artifacts
        path: arch/arm64/boot/Image
